export const PHOTO_PADDING = 15;
export const CAMERA_ICON_SIZE = 30;
export const PHOTO_CONTAINER_PADDING = 10;
export const INPUT_LEFT_COMPONENT_WIDTH =
  CAMERA_ICON_SIZE + (PHOTO_PADDING + PHOTO_CONTAINER_PADDING) * 2;
