export enum ScreenName {
  FOLDER = 'FOLDER',
  SETTINGS = 'SETTINGS',
  MAIN_STACK = 'MAIN_STACK',
  FOLDER_LIST = 'FOLDER_LIST',
  BOTTOM_STACK = 'BOTTOM_STACK',
  FOLDER_LIST_ALL = 'FOLDER_LIST_ALL',
  FOLDER_CREATE_MODAL = 'FOLDER_CREATE_MODAL',
}
