export enum ScreenName {
  FOLDER = 'FOLDER',
  SETTINGS = 'SETTINGS',
  FOLDER_LIST = 'FOLDER_LIST',
  FOLDER_CREATE = 'FOLDER_CREATE',
}

export enum ButtonId {
  FOLDER_CREATE = 'FOLDER_CREATE',
  FOLDER_CREATE_SAVE = 'FOLDER_CREATE_SAVE',
  FOLDER_CREATE_CANCEL = 'FOLDER_CREATE_CANCEL',
}
