export enum ScreenName {
  TOP_STACK = 'TOP_STACK',
  MAIN_STACK = 'MAIN_STACK',
  BOTTOM_STACK = 'BOTTOM_STACK',

  SETTINGS = 'SETTINGS',
  SETTINGS_STACK = 'SETTINGS_STACK',

  FOLDER = 'FOLDER',
  FOLDERS_STACK = 'FOLDERS_STACK',
  FOLDERS_LIST_ALL = 'FOLDERS_LIST_ALL',
  FOLDER_CREATE_MODAL = 'FOLDER_CREATE_MODAL',
}
