require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

abstract_target 'App' do
  target 'InfoCloudDevelopment' do
    #Development-specific pods
  end

  target 'InfoCloudStaging' do
    #Staging-specific pods
  end

  target 'InfoCloud' do
    #Production-specific pods


    target 'InfoCloudTests' do
      inherit! :complete
      # Pods for testing
    end
  end

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
